#cloud-config

groups:
  - consul
  - nomad
users:
  - name: ${username}
    ssh-authorized-keys:
      - ${ssh_public_key}
    sudo: ['ALL=(ALL) NOPASSWD:ALL']
    groups: sudo
    shell: /bin/bash
  - name: consul
    groups: consul
    shell: /bin/bash
  # https://learn.hashicorp.com/tutorials/nomad/production-deployment-guide-vm-with-consul#install-nomad
  # Server as nomad user
  - name: nomad
    groups: nomad
    shell: /bin/false
    system: true
    home: /etc/nomad.d
write_files:
- path: /etc/consul.d/consul.hcl
  permissions: 0644
  owner: root
  content: |
    server = true
    datacenter = "dc1"
    bootstrap_expect = 1
    log_level = "INFO"
    encrypt = "${consul_secret_key}"
    data_dir = "/tmp/consul"
    advertise_addr = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
    connect {
      enabled = true
    }
    node_name = "ctrlplane"
    enable_central_service_config = true
- path: /etc/nomad.d/nomad.hcl
  permissions: 0644
  owner: root
  content: |
    data_dir = "/etc/nomad.d"
    bind_addr = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
    server {
      enabled          = true
      bootstrap_expect = 1
    }
    addresses {
      http = "127.0.0.1"
    }
    advertise {
      http = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
      rpc = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
      serf = "{{ GetPrivateInterfaces | include \"network\" \"10.0.0.0/8\" | attr \"address\" }}"
    }
    consul {
      address             = "127.0.0.1:8500"
      server_service_name = "nomad"
      client_service_name = "nomad-client"
      auto_advertise      = true
      server_auto_join    = true
      client_auto_join    = true
    }
    ui {
      enabled =  true
    }
runcmd:
  - mkdir - /opt/nomad
  - [ systemctl, daemon-reload ]
  - [ systemctl, restart, consul ] 
  - [ systemctl, restart, nomad ] 